eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 14201

spring:
  application:
    name: blog-app
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
    discovery:
      enabled: true
      serviceId: config-server
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 192.168.20.128
    port: 5672
    username: guest
    password: guest

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
