eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 14201

spring:
  application:
    name: blog-app
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
    discovery:
      enabled: true
      serviceId: config-server

feign:
  hystrix:
    enabled: true
